export { default as Header } from './common/Header';
export { default as Footer } from './common/Footer';
export { default as Main } from './bus/Main';
export { default as Detail } from './bus/Detail';
export { default as BusStationMap } from './modal/BusStationMap';
export { default as Faq } from './support/faq/Faq';
export { default as NoticeList } from './support/notice/List';
export { default as NoticeDetail } from './support/notice/Detail';
export { default as Inquiry } from './support/inquiry/Inquiry';